---
- name: Trigger job template when IP address is created or assigned to interface
  hosts: all
  sources:
    - networktocode.nautobot.nautobot_changelog:
        instance: "{{ NAUTOBOT_URL }}"
        token: "{{ NAUTOBOT_TOKEN }}"
        interval: 5
        validate_certs: false

  rules:
    - name: IP address created or updated directly
      condition: >
        event.host is defined
        and event.ip_version is defined
        and event.mask_length is defined
      action:
        run_job_template:
          name: "Nautobot Job Template"
          organization: "Default"
          job_args:
            extra_vars:
              eda_event: "{{ event }}"
              eda_rule_name: "IP address created or updated directly"

    - name: Interface updated (IP assigned or removed)
      condition: >
        event.device is defined
        and event.name is defined
        and event.enabled is defined
        and event.mgmt_only is defined
      action:
        run_job_template:
          name: "Nautobot Job Template"
          organization: "Default"
          job_args:
            extra_vars:
              eda_event: "{{ event }}"
              eda_rule_name: "Interface updated (IP assigned or removed)"
